services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_USERNAME_ROOT=${DB_USERNAME_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}

volumes:
  dbdata:
